services:
  frontend:
    build: frontend
    image: frontend-image
    ports:
      - 8080:8080
    # volumes:
    #   - ./:/frontend
    depends_on:
      - backend
    # network_mode: host

  backend:
    build: backend
    image: backend-image
    ports:
      - 8000:8000
    # expose:
    #   - 8000
    # network_mode: host

    # volumes:
    #   -
# volumes:
#   todo-mysql-data:
